version: '3.2'

services:

  appfabric-service:
    image: appfabric-service.artifactory.eng.vmware.com/appfabric-service
    container_name: appfabric-service
    hostname: appfabric-service
    environment:
      GITLAB_BIFROST_TYPESCRIPT_TOKENS_ID: ${GITLAB_BIFROST_TYPESCRIPT_TOKENS_ID}
      GITLAB_BIFROST_TYPESCRIPT_TOKENS_SECRET: ${GITLAB_BIFROST_TYPESCRIPT_TOKENS_SECRET}
    ports:
      - "8090:8090"
    networks:
      - fabric
    restart: always

  appfabric-ui:
    image: appfabric-service.artifactory.eng.vmware.com/appfabric-ui
    hostname: appfabric-ui
    ports:
      - "80:80"
    networks:
      - fabric
    depends_on:
      - appfabric-service
    restart: always

networks:
  fabric:
    driver: bridge
