swagger: '2.0'
info:
  description: |
    Sample Fabric REST Endpoints
  version: '1.0'
  title: Sample Application Fabric Endpoints
  termsOfService: 'http://appfabric.vmware.com'
  contact:
    name: VMware
  license:
    name: 'Copyright (c) 2019 VMware, Inc. All rights reserved.'
  x-vmw-vapi-codegenconfig:
    packagename: com.vmware.fabric.samples
    tag-resources-by-url-path: true
host: appfabric.vmware.com
basePath: /rest/samples
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

paths:
  /calendar:
    get:
      tags:
        - CalendarService
      summary: Call the CalendarService
      x-vmw-vapi-servicename: calendar
      x-vmw-vapi-methodname: callCalendarSrvice
      x-vmc-ui-servicename: calendar
      parameters:
        - name: calendarRequet
          in: body
          description: Calendar request required.
          required: true
          schema:
            $ref: '#/definitions/CalendarRequest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/SampleResponse'
        '400':
          description: Bad Request, missing something
          schema:
            $ref: '#/definitions/SampleError'
        '500':
          description: Unexpected error.
          schema:
            $ref: '#/definitions/SampleError'

  /pong:
    post:
      tags:
        - PongService
      summary: Call the PongService
      x-vmw-vapi-servicename: pong
      x-vmw-vapi-methodname: callPongService
      x-vmc-ui-servicename: pong
      parameters:
        - name: pingRequest
          in: body
          description: Ping message to be sent.
          required: true
          schema:
            $ref: '#/definitions/PongRequest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/SampleResponse'

        '400':
          description: Bad Request, missing something
          schema:
            $ref: '#/definitions/SampleError'

        '500':
          description: Unexpected error.
          schema:
            $ref: '#/definitions/SampleError'

definitions:
  Frame:
    type: object
    required:
      - payload
    properties:
      id:
        description: UUID of request
        type: string
      version:
        description: version of the request.
        type: integer
      payload:
        description: Payload string to be sent
        type: string

  PongRequest:
    type: object
    required:
      - payload
    allOf:
      - $ref: '#/definitions/Frame'
    properties:
      request:
        description: Request command
        type: string
        enum:
          - basic
          - full

  CalendarRequest:
    type: object
    required:
      - payload
    allOf:
      - $ref: '#/definitions/Frame'
    properties:
      request:
        description: Request command
        type: string
        enum:
          - date
          - time

  SampleResponse:
    type: object
    required:
      - payload
    allOf:
      - $ref: '#/definitions/Frame'

  SampleError:
    type: object
    allOf:
      - $ref: '#/definitions/Frame'
      - properties:
          error:
            description: Is the response an error (defaults to true)
            type: boolean
          errorMessage:
            description: error message if available
            type: string
          errorCode:
            description: error code if available
            type: integer
