swagger: '2.0'
info:
    description: |
        Sample Fabric REST Endpoints
    version: '1.0'
    title: Sample Application Fabric Endpoints
    termsOfService: 'http://appfabric.vmware.com'
    contact:
        name: VMware
    license:
        name: 'Copyright (c) 2019 VMware, Inc. All rights reserved.'
    x-vmw-vapi-codegenconfig:
        packagename: com.vmware.fabric.samples
        tag-resources-by-url-path: true
host: appfabric.vmware.com
basePath: /rest/samples
schemes:
    - http
consumes:
    - application/json
produces:
    - application/json

paths:
    /calendar/time:
        get:
            tags:
                - CalendarService
            summary: Get current time
            x-vmw-vapi-methodname: getTime
            x-vmw-vapi-servicename: calendar
            responses:
                '200':
                    description: OK
                    schema:
                        $ref: '#/definitions/SampleResponse'
                '400':
                    description: Bad Request, missing something
                    schema:
                        $ref: '#/definitions/SampleError'
                '500':
                    description: Unexpected error.
                    schema:
                        $ref: '#/definitions/SampleError'

    /calendar/date:
        get:
            tags:
                - CalendarService
            summary: Get current date
            x-vmw-vapi-methodname: getDate
            x-vmw-vapi-servicename: calendar
            responses:
                '200':
                    description: OK
                    schema:
                        $ref: '#/definitions/SampleResponse'
                '400':
                    description: Bad Request, missing something
                    schema:
                        $ref: '#/definitions/SampleError'

                '500':
                    description: Unexpected error.
                    schema:
                        $ref: '#/definitions/SampleError'

    /pong/basic:
        post:
            tags:
                - PongService
            summary: Get basic pong response
            x-vmw-vapi-methodname: basicPong
            x-vmw-vapi-servicename: pong
            parameters:
                - name: pingRequest
                  in: body
                  description: Ping message to be sent.
                  required: true
                  schema:
                      $ref: '#/definitions/SampleRequest'
            responses:
                '200':
                    description: OK
                    schema:
                        $ref: '#/definitions/SampleResponse'

                '400':
                    description: Bad Request, missing something
                    schema:
                        $ref: '#/definitions/SampleError'

                '500':
                    description: Unexpected error.
                    schema:
                        $ref: '#/definitions/SampleError'

    /pong/full:
        post:
            tags:
                - PongService
            summary: Get a full pong response (Calls CalendarService)
            x-vmw-vapi-methodname: fullPong
            x-vmw-vapi-servicename: pong
            parameters:
                - name: pingRequest
                  in: body
                  description: Ping message to be sent.
                  required: true
                  schema:
                      $ref: '#/definitions/SampleRequest'
            responses:
                '200':
                    description: OK
                    schema:
                        $ref: '#/definitions/SampleResponse'

                '400':
                    description: Bad Request, missing something
                    schema:
                        $ref: '#/definitions/SampleError'

                '500':
                    description: Unexpected error.
                    schema:
                        $ref: '#/definitions/SampleError'

definitions:
    Frame:
        type: object
        required:
            - payload
        properties:
            id:
                description: UUID of request
                type: string
            created:
                description: timestamp of when the request was created
                type: number
            version:
                description: version of the request.
                type: integer
            payload:
                description: Payload string to be sent
                type: string

    SampleRequest:
        type: object
        required:
            - payload
        allOf:
            - $ref: '#/definitions/Frame'

    SampleResponse:
        type: object
        required:
            - payload
        allOf:
            - $ref: '#/definitions/Frame'

    SampleError:
        type: object

        allOf:
            - $ref: '#/definitions/Frame'
            - properties:
                  error:
                      description: Is the response an error (defaults to true)
                      type: boolean
                  errorMessage:
                      description: error message if available
                      type: string
                  errorCode:
                      description: error code if available
                      type: integer

