logging.level:
  vmware.bifrost: DEBUG
  messageFabricSamples: DEBUG
  root: WARN
  org.springframework.web: INFO

spring:
  output.ansi.enabled: always
  mvc.favicon.enabled: false
  profiles.active: prod

server.port: 8090
messages:
  service:
    type: CLOUD
    name: bifrost-sample-cloud-service
    identity: dfafb926-d581-4a59-89ad-adee1f9424ce
    host: localhost
    port: 8090

  broker:
    host: localhost
    port: 8080
